import Whatsnew from "../../support/Page Object/Advisor/Whatsnew"
import Home from "../../support/Page Object/Advisor/Home"
import Partner from "../../support/Page Object/Advisor/Partner"
import Newhome from "../../support/Page Object/Advisor/Newhome"
import Marketing from "../../support/Page Object/Advisor/Marketing";

describe('Advisor_Whatsnew_TS001',{ testIsolation: false }, function() {
    before(() => {
     
      cy.then(Cypress.session.clearCurrentSessionData)
      cy.on('uncaught:exception', (err,runnable) => { 
        return false
    })
   cy.clearAllLocalStorage()
    })
      
    it('Advisor_Whatsnew_TC001_To verify the Whatsnew section', () => {
          cy.on('uncaught:exception', (err,runnable) => { 
              return false
          })    
         
         //cy.Login1()
         cy.NotanadvisorLogin()

         Home.navbar.click()
         Marketing.Resource.click()
         cy.wait(5000)
        // Whatsnew.Whatsnewicon.should('be.visible')
         Whatsnew.Whatsnew.scrollIntoView().should('be.visible').click()
         cy.url().should('include', 'https://advisor.forastaging.net/whats-new');
         Whatsnew.Whatsnewheader.should('be.visible')
       //  Whatsnew.Whatsnewsection.eq(0).should('be.visible')
         Whatsnew.Whatsnewsection.eq(1).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewleftsection.eq(0).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewleftsection.eq(1).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewsubheader.eq(0).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewsubheader.eq(1).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewdate.eq(0).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewdate.eq(1).scrollIntoView().should('be.visible')
         Whatsnew.Whatsnewtag.should('be.visible')

        })

        it('Advisor_Whatsnew_TC002_To verify the Report an issue module', () => {
            cy.on('uncaught:exception', (err,runnable) => { 
                return false
            }) 
            Home.navbar.click()
            Partner.Reportanissue.scrollIntoView().click()
      cy.wait(5000)
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
     /* Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      cy.wait(2000)
      Partner.dropdownvalue1.should('be.visible')
      Partner.dropdownvalue2.should('be.visible')
      Partner.dropdownvalue3.should('be.visible')
      Partner.dropdownvalue4.should('be.visible')
      Partner.dropdownvalue5.should('be.visible')
      Partner.dropdownvalue6.should('be.visible')
      
      Partner.dropdownvalue1.click()
      Partner.Describetheissue.should('be.visible')
      Partner.Describetheissuefield.should('be.visible')
      Partner.Cancel.should('be.visible')
      Partner.Report.should('be.visible').click()
      //Partner.Error1.should('be.visible')
      Partner.Error2.should('be.visible')
      Partner.Issueseverityheader.should('be.visible')
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue1.should('be.visible')
      Partner.Issueseveritydropdownvalue2.should('be.visible')
      Partner.Issueseveritydropdownvalue3.should('be.visible')
      Partner.Issueseveritydropdownvalue2.should('be.visible').click()
      Partner.Describetheissuefield.should('be.visible').type("error")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()*/
     // Partner.Reportanissue.scrollIntoView().click()
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
      Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      Partner.dropdownvalue1.should('be.visible')
      Partner.dropdownvalue2.should('be.visible')
      Partner.dropdownvalue3.should('be.visible')
      Partner.dropdownvalue4.should('be.visible')
      Partner.dropdownvalue5.should('be.visible')
      Partner.dropdownvalue6.should('be.visible')
      cy.wait(2000)
      Partner.dropdownvalue2.click()
      cy.wait(2000)
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue2.click()
      Partner.Issuetypeheader.should('be.visible')
      Partner.Issuetypedropdown.click()
      Partner.Issuetypedropdown1.should('be.visible')
      Partner.Issuetypedropdown2.should('be.visible')
      Partner.Issuetypedropdown3.should('be.visible')
      Partner.Issuetypedropdown4.should('be.visible')
      Partner.Issuetypedropdown5.eq(4).should('be.visible')
      Partner.Issuetypedropdown2.click()
      Partner.Describetheissuefield.should('be.visible').type("error")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()
      //Marketing
    /*  Home.navbar.click()
      Partner.Reportanissue.scrollIntoView().click()
      cy.wait(2000)
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
      Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      Partner.dropdownvalue3.click()
      cy.wait(2000)
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue3.should('be.visible').click()
      cy.wait(2000)
      Partner.Issuetypedropdown.click()
      Partner.Marketingissuetypedropdown1.should('be.visible')
      Partner.Marketingissuetypedropdown2.should('be.visible')
      Partner.Marketingissuetypedropdown3.should('be.visible')
      Partner.Marketingissuetypedropdown4.should('be.visible')
      Partner.Marketingissuetypedropdown5.should('be.visible')
      Partner.Marketingissuetypedropdown6.should('be.visible')
      Partner.Marketingissuetypedropdown7.eq(6).should('be.visible')
      Partner.Marketingissuetypedropdown3.click()
      Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()
      ////Partners
      Home.navbar.click()
      Partner.Reportanissue.scrollIntoView().click()
      cy.wait(2000)
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
      Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      Partner.dropdownvalue4.click()
      cy.wait(2000)
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue2.should('be.visible').click()
      cy.wait(2000)
      Partner.Issuetypedropdown.click()
      Partner.Partnerissuetypedropdown1.should('be.visible')
      Partner.Partnerissuetypedropdown2.should('be.visible')
      Partner.Partnerissuetypedropdown3.should('be.visible')
      Partner.Partnerissuetypedropdown4.should('be.visible')
      Partner.Partnerissuetypedropdown5.should('be.visible')
      Partner.Partnerissuetypedropdown6.eq(5).should('be.visible')
      Partner.Partnerissuetypedropdown5.should('be.visible').click()
      Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()
      //General feedback
      Home.navbar.click()
      Partner.Reportanissue.scrollIntoView().click()
      cy.wait(2000)
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
      Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      Partner.dropdownvalue6.click()
      cy.wait(2000)
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue3.should('be.visible').click()
      cy.wait(2000)
      Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()
      cy.wait(2000)
      /// Training
      Home.navbar.click()
      Partner.Reportanissue.scrollIntoView().click()
      cy.wait(2000)
      Partner.Reportanissueheader.should('be.visible')
      Partner.Reportanissuetext.should('be.visible')
      Partner.Issuetopicheader.should('be.visible')
      Newhome.issuetypedropdown.should('be.visible').eq(0).click()
      Partner.dropdownvalue5.click()
      Partner.Issueseveritydropdown.click()
      Partner.Issueseveritydropdownvalue3.should('be.visible').click()
      cy.wait(2000)
      Partner.Issuetypedropdown.click()
      Partner.Trainerissuetypedropdown1.should('be.visible')
      Partner.Trainerissuetypedropdown2.should('be.visible')
      Partner.Trainerissuetypedropdown3.should('be.visible')
      Partner.Trainerissuetypedropdown4.should('be.visible')
      Partner.Trainerissuetypedropdown5.should('be.visible')
      Partner.Trainerissuetypedropdown6.should('be.visible')
      Partner.Trainerissuetypedropdown7.should('be.visible')
      Partner.Trainerissuetypedropdown8.eq(7).should('be.visible')
      Partner.Trainerissuetypedropdown3.should('be.visible').click()
      cy.wait(2000)
      Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
      Partner.Report.click()
      Partner.rightmarks.should('be.visible')
      Partner.successtext.should('be.visible')
      Partner.successsubtext.should('be.visible')
      Partner.close.click()
      cy.wait(2000)
     */

        })
    })