import Leads from "../../support/Page Object/Advisor/Leads"

describe('Advisor_Leads_TS001',{ testIsolation: false }, function() {
    before(() => {
        // ensure clean test slate for these tests
        cy.then(Cypress.session.clearCurrentSessionData)
      })
      it('Advisor_Leads_TC001_To verify ',() => {
   
        cy.on('uncaught:exception', (err,runnable) => { 
            return false
        })   

        cy.visit('https://foratravel.typeform.com/to/uTw5bh2q')
        Leads.Readytobook.should('be.visible')
        Leads.Connectwithanadvisor.should('be.visible')
        Leads.Connectwithanadvisor1.should('be.visible')
        Leads.Browsingaround.should('be.visible')
        Leads. Checkoutour.should('be.visible')
     //   Leads.Partner.should('be.visible').click()
       // Leads.FAQS.should('be.visible').click()
        Leads.Getstarted.should('be.visible').click()
        cy.wait(2000)
        Leads.Wheredoyouwanttogo.should('be.visible')
        
        Leads.Wheredoyouwanttogotextbox.should('be.visible').type('India')
        Leads.OKbutton.eq(0).click()
        Leads.Whenwouldyouliketotravel.should('be.visible')
        Leads.Whenwouldyouliketotraveltext.should('be.visible')

        Leads.Whenwouldyouliketotraveltextbox.should('be.visible').type('December')
        Leads.OKbutton.eq(1).click()
        cy.wait(3000)
        Leads.Howmanydaysyouwanttotravel.should('be.visible')
        Leads.Howmanydaysyouwanttotravel1.should('be.visible')
        Leads.twotothree.should('be.visible')
        Leads.threetoseven.should('be.visible')
        Leads.seventofourteen.should('be.visible')
        Leads.fourteenplus.should('be.visible')
        Leads.twotothree.should('be.visible').click()
Leads.Howmanywillbetravelling.should('be.visible')
Leads.Oneperson.should('be.visible')
Leads.Twoperson.should('be.visible')
Leads.Threetofiveperson.should('be.visible')
Leads.Fiveplusperson.should('be.visible')
Leads.Oneperson.should('be.visible').click()
cy.wait(3000)
//Leads.Travellingwithchildren.should('be.visible')
Leads.yes.click()
Leads.Whatsyourbudget.should('be.visible')
Leads.twofiftytofivehundread.should('be.visible')
Leads.Fivehundreadtosevenfifty.should('be.visible')
Leads.Sevenfiftyplus.should('be.visible').click()
Leads.totaltripbudget.should('be.visible')
Leads.totaltripbudgettextbox.type("8888")
Leads.totaltripbudgetokbutton.click()
Leads.Whatlevelofservice.should('be.visible')
Leads.Hotelbookingonly.should('be.visible')
Leads.Cruisebookingonly.should('be.visible')
Leads.BookingplusCustomItinerary.should('be.visible').click()
Leads.Firstname.should('be.visible')
Leads.Lastname.should('be.visible')
Leads.Firstnamefield.type('Test')
Leads.Lastnamefield.type('QA')
Leads.Phonenumber.should('be.visible')
Leads.Phoneneumberfield.type('512 566 4855')
Leads.Emailform.should('be.visible')

Leads.Emailfield.type('reenaz.qa123@forastaging.net')
Leads.ContactOkbutton.click()
cy.wait(2000)
Leads.Preferredmethodofcommunication.should('be.visible')
Leads.ContactEmail.should('be.visible')
Leads.Text.should('be.visible')
Leads.Phonecall.should('be.visible')
Leads.ContactEmail.should('be.visible').click()
Leads.Anyotherdetails.should('be.visible')
Leads.Anyotherdetails1.should('be.visible')
Leads.Anyotherdetailstextfeild.type('No other details')
Leads.Anyotherdetailsokay.click()
cy.wait(2000)

Leads.Lastquestion.should('be.visible')
Leads.google.should('be.visible')
Leads.article.should('be.visible')
Leads.Instagram.should('be.visible')
Leads.Tiktok.should('be.visible')
Leads.Othersocialmedia.should('be.visible')
Leads.Wordofmouth.scrollIntoView().should('be.visible')
Leads.Foraadvisor.scrollIntoView().should('be.visible')
Leads.other.scrollIntoView().should('be.visible')
Leads.Instagram.should('be.visible').click()
Leads.Submit.scrollIntoView().click()
cy.wait(1000)
Leads.Thankyou.should('be.visible')
Leads.Youwillreceiveareply.should('be.visible')
    })
})