


import Home from "../../support/Page Object/Advisor/Home"
import Bookings from "../../support/Page Object/Advisor/Booking"
import Partner from "../../support/Page Object/Advisor/Partner"

describe('Advisor_Booking_Report an isuue_TS001', { testIsolation: false },function() {
  before(() => {
    cy.then(Cypress.session.clearCurrentSessionData)
  })



it('Advisor_Booking_To verify the Report an issue in bookings page- Validating all the dropdowns in report an issue ', () => {
    cy.on('uncaught:exception', (err, runnable) => {
      return false;
    });
  cy.NotanadvisorLogin()
  Home.navbar.click()
  Bookings.booking.click() 
  Home.navbar.click()
  Partner.Reportanissue.click()

  Partner.Issuetopicheader.should('be.visible')
  Partner.Issuetopicdropdown.should('be.visible').click()
  Partner.dropdownvalue1.should('be.visible')
Partner.dropdownvalue2.should('be.visible')
Partner.dropdownvalue3.should('be.visible')
Partner.dropdownvalue4.should('be.visible')
Partner.dropdownvalue5.should('be.visible')
Partner.dropdownvalue6.should('be.visible')
Partner.dropdownvalue7.should('be.visible')
Partner.Testpaymentdropdown.should('be.visible')
Partner.dropdownvalue1.click()
Partner.Describetheissue.should('be.visible')
Partner.Describetheissuefield.should('be.visible')
Partner.Cancel.should('be.visible')
Partner.Report.should('be.visible').click()
//Partner.Error1.should('be.visible')
Partner.Error2.should('be.visible')
Partner.Issueseverityheader.should('be.visible')
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue1.should('be.visible')
Partner.Issueseveritydropdownvalue2.should('be.visible')
Partner.Issueseveritydropdownvalue3.should('be.visible')
Partner.Issueseveritydropdownvalue2.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("error")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
Home.navbar.click()
Partner.Reportanissue.click()

Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue1.should('be.visible')
Partner.dropdownvalue2.should('be.visible')
Partner.dropdownvalue3.should('be.visible')
Partner.dropdownvalue4.should('be.visible')
Partner.dropdownvalue5.should('be.visible')
Partner.dropdownvalue6.should('be.visible')
Partner.dropdownvalue2.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue2.click()
Partner.Issuetypeheader.should('be.visible')
Partner.Issuetypedropdown.click()
cy.wait(2000)
Partner.Issuetypedropdown1.should('be.visible')
Partner.Issuetypedropdown2.should('be.visible')
Partner.Issuetypedropdown3.should('be.visible')
Partner.Issuetypedropdown4.should('be.visible')
Partner.Issuetypedropdown5.should('be.visible')
Partner.Issuetypedropdown2.click()
Partner.Describetheissuefield.should('be.visible').type("error")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
///////////////////////////Marketing
Home.navbar.click()
Partner.Reportanissue.click()

Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue3.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue3.should('be.visible').click()
Partner.Issuetypedropdown.click()
Partner.Marketingissuetypedropdown1.should('be.visible')
Partner.Marketingissuetypedropdown2.should('be.visible')
Partner.Marketingissuetypedropdown3.should('be.visible')
Partner.Marketingissuetypedropdown4.should('be.visible')
Partner.Marketingissuetypedropdown5.should('be.visible')
Partner.Marketingissuetypedropdown6.should('be.visible')
Partner.Marketingissuetypedropdown7.should('be.visible')
Partner.Marketingissuetypedropdown3.click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
cy.wait(2000)
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
//////////////////Partners
Home.navbar.click()
Partner.Reportanissue.click()

Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue4.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue2.should('be.visible').click()
Partner.Issuetypedropdown.click()
Partner.Partnerissuetypedropdown1.should('be.visible')
Partner.Partnerissuetypedropdown2.should('be.visible')
Partner.Partnerissuetypedropdown3.should('be.visible')
Partner.Partnerissuetypedropdown4.should('be.visible')
Partner.Partnerissuetypedropdown5.should('be.visible')
Partner.Partnerissuetypedropdown6.should('be.visible')
Partner.Partnerissuetypedropdown5.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
///////////////////////General feedback
Home.navbar.click()
Partner.Reportanissue.click()
Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue7.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue3.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
/////////////////////// Training
Home.navbar.click()
Partner.Reportanissue.click()
Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue6.click()
cy.wait(2000)
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue3.should('be.visible').click()
Partner.Issuetypedropdown.click()
Partner.Trainerissuetypedropdown1.should('be.visible')
Partner.Trainerissuetypedropdown2.should('be.visible')
Partner.Trainerissuetypedropdown3.should('be.visible')
Partner.Trainerissuetypedropdown4.should('be.visible')
Partner.Trainerissuetypedropdown5.should('be.visible')
Partner.Trainerissuetypedropdown6.should('be.visible')
Partner.Trainerissuetypedropdown7.should('be.visible')
Partner.Trainerissuetypedropdown8.should('be.visible')
Partner.Trainerissuetypedropdown3.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()

/////////////////////// Payement
Home.navbar.click()
Partner.Reportanissue.click()
Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.dropdownvalue5.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue3.should('be.visible').click()
Partner.Issuetypedropdown.click()
Partner.paymentdropdown1.should('be.visible')
Partner.paymentdropdown2.should('be.visible')
Partner.paymentdropdown3.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
/////////////////////// Test Payement
Home.navbar.click()
Partner.Reportanissue.click()
Partner.Reportanissueheader.should('be.visible')
Partner.Reportanissuetext.should('be.visible')
Partner.Issuetopicheader.should('be.visible')
Partner.Issuetopicdropdown.should('be.visible').eq(0).click()
Partner.Testpaymentdropdown.click()
Partner.Issueseveritydropdown.click()
Partner.Issueseveritydropdownvalue3.should('be.visible').click()
Partner.Issuetypedropdown.click()
Partner.Testpaymentdropdown1.should('be.visible')
Partner.Testpaymentdropdown2.should('be.visible')
Partner.Testpaymentdropdown3.should('be.visible')

Partner.Testpaymentdropdown1.should('be.visible').click()
Partner.Describetheissuefield.should('be.visible').type("Testttttttttttttt")
Partner.Report.click()
Partner.rightmarks.should('be.visible')
Partner.successtext.should('be.visible')
Partner.successsubtext.should('be.visible')
Partner.close.click()
})
it('Advisor_CopyIATA_TC001 _To verify the IATA copy buton', () => {
  cy.on('uncaught:exception', (err,runnable) => { 
      return false
  })  
  Home.navbar.click()
  cy.wait(2000)
Home.CopyIATAbutton.click()
//cy.get('[id="custom-tooltip-1"]').invoke('show').should('have.text', 'copied!');


})
})